name: GITHUB_OUTPUT
run-name: Run by @${{ github.actor }}
on: push
#   inputs:
#      greeting:
#        type: string
#        default: Hello
#        required: true
#        description: A cheerful word
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "$S{GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
          run: echo "${RESULT}"



