name: GITHUB_OUTPUT
run-name: Run by @${{ github.actor }} from ${{ github.ref_name }}
on: pull_request
#   inputs:
#      greeting:
#        type: string
#        default: Hello
#        required: true
#        description: A cheerful word
jobs:
  share:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


